---
- name: create a directory
  hosts: localhost
  tasks:
  - name: create a volume
    file:
      name: containers
      state: directory
      path: /home/krarjunjha/

  - name: installing podman
    package:
      name: "podman"
      state: present

  - name: Pull an image
    podman_image:
      name: httpd

  - name: creating a container    
    containers.podman.podman_container:
      name: apache
      image: docker.io/httpd
      volumes:
        - "/home/krarjunjha/containers:/usr/local/apache2/htdocs"
      state: started
      detach: true
      ports:
       - 8081:80
